language: bash

env: 
    - tf_version=0.12.29

before_install: 
  - wget https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip
  - unzip terraform_${tf_version}_linux_amd64.zip
  - sudo mv terraform /usr/local/bin
  - rm terraform_${tf_version}_linux_amd64.zip
    
jobs:
  include:
    - stage: terraform plan
      name: terraform plan
      if: NOT branch = master
      script:
        - terraform -v
        - terraform init
        - terraform validate
        - terraform plan
    - stage: terraform apply
      name: terraform apply
      if: branch = master
      script:
        - terraform appy --auto-approve
        
 
